!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO: []
mEncoders:
- mConnectedSpeedControllerHandle: 101
  mHandle: 101
  mName: Left Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 104
  mHandle: 104
  mName: Right Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 109
  mHandle: 109
  mName: Disker Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
mGyros: []
mPwm:
- mHandle: 101
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Left Master
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 102
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Left Follower A
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Left Follower B
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 104
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Right Master
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 105
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Right Follower A
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 106
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Right Follower B
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 109
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 80000.0
  mName: CTRE SC 9
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents: []
mSolenoids:
- mHandle: 0
  mName: Gear Shifter Forward
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 1
  mName: Gear Shifter Reverse
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
