!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO:
- mHandle: 0
  mName: Turret Limit Switch
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
- mHandle: 1
  mName: Angler Limit Switch
  mType: com.snobot.simulator.module_wrapper.wpi.WpiDigitalIoWrapper
mEncoders:
- mConnectedSpeedControllerHandle: 101
  mHandle: 101
  mName: Left Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 104
  mHandle: 104
  mName: Right Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 109
  mHandle: 109
  mName: Disker Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 111
  mHandle: 111
  mName: Turret Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 112
  mHandle: 112
  mName: Angler Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
- mConnectedSpeedControllerHandle: 113
  mHandle: 113
  mName: Launcher Encoder
  mType: com.snobot.simulator.simulator_components.smart_sc.SmartScEncoder
mGyros: []
mPwm:
- mHandle: 101
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Left Master
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 102
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Left Follower A
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Left Follower B
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 104
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Right Master
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 105
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Right Follower A
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 106
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Right Follower B
  mType: com.snobot.simulator.simulator_components.rev.RevSpeedControllerSimWrapper
- mHandle: 107
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Intake Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 108
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Snail Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 109
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 80000.0
  mName: Disker Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 110
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Elevator Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 111
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Turret Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 112
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Angler Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 113
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Launcher Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 114
  mMotorModelConfig: null
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.SimpleMotorSimulationConfig
    mMaxSpeed: 0.0
  mName: Climber Motor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents: []
mSolenoids:
- mHandle: 0
  mName: Gear Shifter Forward
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 1
  mName: Gear Shifter Reverse
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 2
  mName: Intake Forward
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
- mHandle: 3
  mName: Intake Reverse
  mType: com.snobot.simulator.module_wrapper.wpi.WpiSolenoidWrapper
